name: DevSecOps Pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/*.tf'
      - 'app/*'
      - '.github/workflows/devsecops.yaml'
  
  push:
    branches:
      - development



jobs:

#####################################
#  GENERICS
#####################################

  BASSICS-CICD:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for secrets (Gitleaks)
        id: gitleaks_check
        uses: zricethezav/gitleaks-action@v2
        continue-on-error: ${{ env.CONTINUE_ON_WORKFLOW_ERRORS }} # Para que el workflow no se detenga

      - name: Slack Notification
        if: steps.gitleaks_check.outcome == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL:  ${{ env.SLACK_CHANNEL }}
          SLACK_COLOR:    '#fc0303'
          SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}          
          SLACK_TITLE:    ':skull: Gitleaks'
          SLACK_MESSAGE:  'I found a security problem in this commit: ${{ github.sha }}'


#####################################
#  INFRAESTRUCTURE
#####################################

  INFRASTRUCTURE-CICD:
    runs-on: ubuntu-latest
    env:
      TF_OUTPUT_PATH:         '/tmp/output'
      TF_CONTINUNE_ON_ERR:    true
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2


      - name: Terraform init
        run: |
          terraform -chdir=terraform/ init -input=false


      - name: Terraform Validate
        id: tf_validate
        continue-on-error: true
        run: terraform -chdir=terraform/ validate


      - name: Terraform Validate Fails (Slack)
        if: steps.tf_validate.outcome == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          SLACK_COLOR: '#b204c9'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}          
          SLACK_TITLE: ':img_terraform: Terraform validation'
          SLACK_MESSAGE: 'Terraform validate has failed. Please check your code with `terraform validate`.'


      - name: Terraform Format
        id: terraform_fmt
        run: |
          set +e
          terraform -chdir=terraform/ fmt -check
          echo "FMT_EXIT_CODE=$?" >> $GITHUB_ENV
          exit 0


      - name: Terraform format Fails (Slack)
        if: env.FMT_EXIT_CODE != '0'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL:  ${{ env.SLACK_CHANNEL }}
          SLACK_COLOR:    '#b204c9'
          SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}          
          SLACK_TITLE:    ':img_terraform: Terraform format validator'
          SLACK_MESSAGE: |
            'Terraform format validation has failed. 
            ${{ env.GIT_COMMIT_AUTHOR_NAME }} please check your code with `terraform fmt` next time   ;) '


      - name: Terraform Security Scan
        continue-on-error: true
        run: |
          mkdir -p ${{ env.TF_OUTPUT_PATH }} 
          chown -R $USER:$USER ${{ env.TF_OUTPUT_PATH }} 
          docker run \
            --rm \
            -v $PWD/terraform/:/data \
            -v ${{ env.TF_OUTPUT_PATH }}:${{ env.TF_OUTPUT_PATH }} \
            aquasec/tfsec --no-color \
            -m CRITICAL \
            -O ${{ env.TF_OUTPUT_PATH }}/output.txt /data


      - name: Show TF Security Scan
        run: |
          cat ${{ env.TF_OUTPUT_PATH }}/output.txt


      - name: Security policy checks (Checkov)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/


#####################################
#  APPLICATIONS
#####################################

  APLICATION-CICD:
    env:
      DH_REPO_OWNER:    'jpradoar'
      REPO_APP:         'mqtt-customer-portal'
      BUILD_CONTEXT:    './02-customer-portal'
      #
      SLACK_CHANNEL:    'builds-and-ci'
      SLACK_MSG_COLOR:  '#0092ff'
      COMMITER_NAME:    'AutoCommit'
      VULN_SEVERITY:    'CRITICAL'
      VULN_TYPE:        'os,library'
      VULN_FORMAT:      'table'
      VULN_TIMEOUT_SCAN: '2m0s'
      VULN_SCANNERS:    'vuln,secret,misconfig,license'
      VULN_IGNORED_LIC: 'MIT' # MIT,LGPL,MPL-2.0
      VULN_EXIT_CODE:   1
      TRIVY_DISABLE_VEX_NOTICE: true
      TRIVY_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:2'

    runs-on: ubuntu-latest
    permissions:
      contents:         write
      security-events:  write
      actions:          read
      issues:           write

    steps:


    - name: Checkout
      uses: actions/checkout@v4


    - name: Python static code analysis (Bandit)
      run: |
        pip install bandit
        bandit -r app/









    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DH_REPO_OWNER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Show last version of docker-hub image
      id: last_version_remote_file
      run: |
        LastVersion=$(curl -s "https://hub.docker.com/v2/repositories/${{ env.DH_REPO_OWNER }}/${{ env.REPO_APP }}/tags/?page_size=2" | jq -r '.results[].name'|sort -M|grep -v latest|tail -1)
        echo "LAST_VERSION=$LastVersion " >> "$GITHUB_OUTPUT"


    - name: Generate new version with semantic version
      id: nversion
      uses: jpradoar/ga-semanticversion@v1.0.0
      with:
        COMMIT_MSG:  ${{ github.event.head_commit.message }}
        VERSION: ${{ steps.last_version_remote_file.outputs.LAST_VERSION }}


    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.BUILD_CONTEXT }}
        push: true
        tags: ${{ env.DH_REPO_OWNER }}/${{ env.REPO_APP }}:${{ steps.nversion.outputs.NEW_VERSION }}


    - name: Install trivy last version
      run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy


    - name: search for vulnerabilities
      id: trivy_scan
      continue-on-error: true
      run: |
        rm -rf ./vuln_scans/${{ env.REPO_APP }}_vuln_scan.table
        trivy image \
         --scanners ${{ env.VULN_SCANNERS }} \
         --severity ${{ env.VULN_SEVERITY }} \
         --timeout ${{ env.VULN_TIMEOUT_SCAN }} \
         --pkg-types ${{ env.VULN_TYPE }} \
         --license-full \
         --ignored-licenses ${{ env.VULN_IGNORED_LIC }} \
         --format ${{ env.VULN_FORMAT }} \
         --exit-code ${{ env.VULN_EXIT_CODE }} \
         --db-repository ${{ env.TRIVY_REPOSITORY }} \
         --ignore-unfixed \
         -o ./vuln_scans/${{ env.REPO_APP }}_vuln_scan.table \
        '${{ env.DH_REPO_OWNER }}/${{ env.REPO_APP }}:${{ steps.nversion.outputs.NEW_VERSION }}'


    - name: show vulnerability report
      if: ${{ steps.trivy_scan.outcome == 'failure' }}
      run: |
        cat ./vuln_scans/${{ env.REPO_APP }}_vuln_scan.table


    - name: validate if exist vuln
      if: ${{ steps.trivy_scan.outcome == 'failure' }}
      run: |
        echo "### See detailed information in: " > /tmp/vuln_info.md
        echo "<br>![](https://custom-icon-badges.demolab.com/badge/Vulnerability-detected-red.svg) ![](https://custom-icon-badges.demolab.com/badge/Affected_version-${{ steps.nversion.outputs.NEW_VERSION }}-purple.svg) <br>" >> /tmp/vuln_info.md
        echo " * Detected in image: [${{ env.REPO_APP }}](https://hub.docker.com/repository/docker/${{ env.DH_REPO_OWNER }}/${{ env.REPO_APP }}/general)" >> /tmp/vuln_info.md
        echo " * Detected in commit: ${{ github.sha }}"  >> /tmp/vuln_info.md
        echo " * Vulnerability report: [vuln_report](https://github.com/${{ GITHUB_REPOSITORY_OWNER }}/${{ GITHUB_REPOSITORY }}/blob/main/vuln_scans/${{ env.REPO_APP }}_vuln_scan.table)" >> /tmp/vuln_info.md


    - name: update data
      if: ${{ steps.trivy_scan.outcome == 'failure' }}
      run: |
          git pull


    - name: Upload vuln scan report
      uses: EndBug/add-and-commit@v9
      with:
        message: 'AutoCommit: upload vuln scan report'
        add: './vuln_scans/${{ env.REPO_APP }}_vuln_scan.table'


    - name: Vulnerability detected - Create Github issue
      if: ${{ steps.trivy_scan.outcome == 'failure' }}
      run: |
        body="New vulnerability detected on vuln_scans/${{ env.REPO_APP }}_vuln_scan.table"
        gh issue create \
        --repo ${{ github.repository }} \
        --title ":skull: [vuln] vulnerability detected on image ${{ env.REPO_APP }} " \
        --body-file '/tmp/vuln_info.md' \
        --assignee "jpradoar" \
        --label bug --label vulnerability
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Slack docker build Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL:  ${{ env.SLACK_CHANNEL }}
        SLACK_COLOR:    ${{ env.SLACK_MSG_COLOR }}
        SLACK_MESSAGE:  'URL: https://hub.docker.com/repository/docker/jpradoar/${{ env.REPO_APP }}'
        SLACK_TITLE:    ':rocket: GithubAction Build docker image: [ ${{ env.REPO_APP }}:${{ steps.nversion.outputs.NEW_VERSION }} ]'
        SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}


    - name: Slack Vulnerability Notification
      if: ${{ steps.trivy_scan.outcome == 'failure' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL:  ${{ env.SLACK_CHANNEL }}
        SLACK_COLOR:    ${{ env.SLACK_MSG_COLOR }}
        SLACK_MESSAGE:  'URL: https://hub.docker.com/repository/docker/jpradoar/${{ env.REPO_APP }}'
        SLACK_TITLE:    ':skull: Vulnerability detected in: [ ${{ env.REPO_APP }}:${{ steps.nversion.outputs.NEW_VERSION }} ]'
        SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}
