name: DevSecOps Pipeline
on:
  
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/*.tf'
      - '.github/workflows/devsecops.yaml'
  
  push:
    branches:
      - development
#    paths:
#      - 'terraform/**'
#      - '.github/workflows/devsecops.yaml'


env:
  SLACK_CHANNEL: 'general'
  SLACK_MSG_COLOR: '#0092ff'

jobs:

#####################################
#  GENERICS
#####################################
  BASSICS-CICD:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for secrets (Gitleaks)
        id: gitleaks_check
        uses: zricethezav/gitleaks-action@v2
        continue-on-error: true  # Para que el workflow no se detenga

      - name: Slack Notification
        if: steps.gitleaks_check.outcome == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL:  ${{ env.SLACK_CHANNEL }}
          SLACK_COLOR:    '#fc0303'
          SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}          
          SLACK_TITLE:    ':warning: Gitleaks'
          SLACK_MESSAGE:  'Gitleaks found a security problem!!!'
